// Code generated by goctl. DO NOT EDIT.
// Source: app.proto

package server

import (
	"context"

	"app/rpc/appserver"
	"app/rpc/internal/logic"
	"app/rpc/internal/svc"
)

type AppServer struct {
	svcCtx *svc.ServiceContext
	appserver.UnimplementedAppServer
}

func NewAppServer(svcCtx *svc.ServiceContext) *AppServer {
	return &AppServer{
		svcCtx: svcCtx,
	}
}

func (s *AppServer) ListStu(ctx context.Context, in *appserver.StuListReq) (*appserver.StuListResp, error) {
	l := logic.NewListStuLogic(ctx, s.svcCtx)
	return l.ListStu(in)
}
