// Code generated by goctl. DO NOT EDIT.
package types

type Student struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
	City string `json:"city"`
}

type BaseResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Uid     string `json:"uid"`
}

type AddStuReq struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
	City string `json:"city"`
}

type AddStuResp struct {
	BaseResponse
	Success bool `json:"success"`
}

type UpdateStuReq struct {
	Id int `path:"id"`
	AddStuReq
}

type UpdateStuResp struct {
	AddStuResp
}

type ListStuReq struct {
	City string `json:"city,optional"`
	Name string `json:"name,optional"`
	With string `form:"with,optional,default=and,options=and|or"`
}

type ListStuResp struct {
	BaseResponse
	List []*Student `json:"list"`
}
